trigger:
  branches:
    include:
    - '*'
variables:
  system_accesstoken: $(System.AccessToken)

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true    #Allow scripts to access the system token
  clean: true 

- task: Bash@3
  name: SyncRepo
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email "emil.garipov@gmail.com"
      git config --global user.name "egaripov"
      git remote set-url origin https://EmilGaripov@dev.azure.com/EmilGaripov/LocalGoods/_git/LocalGoods-front.git
      git remote add upstream https://github.com/emilgaripov/LocalGoods-front.git
      git fetch upstream
      git remote -v
      git checkout
      git branch -m main
      git pull --rebase origin main
      git push -u https://$(System.AccessToken)@dev.azure.com/EmilGaripov/LocalGoods/_git/LocalGoods-front.git origin main