name: Fork Sync

on

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Sync and merge upstream repository with your current repository
      uses: dabreadman/sync-upstream-repo@v1.3.0
      with:
        # URL of gitHub public upstream repo
        upstream_repo: https://github.com/FortisBs/LocalGoods
          # Branch to merge from upstream (defaults to downstream branch)
        upstream_branch: # optional, default is main
          # Branch to merge into downstream
        downstream_branch: # optional, default is 
          # GitHub Bot token
        token: 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
